[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build_x86-64]
command = "cargo"
args = ["build", "--target", "src/arch/x86_64/x86_64.json"]

[tasks.qemu_x86-64]
dependencies = ["build_x86-64"]
script = [
 "cd target/x86_64/debug/",
 "mkdir -p iso/boot/grub",
 "echo \"set timeout=0\nset default=0\n\nmenuentry \"BMetalHV\" { \n\tmultiboot2 /boot/baremetal_hypervisor \n\tboot \n}\" > iso/boot/grub/grub.cfg",
 "cp baremetal_hypervisor iso/boot",
 "grub-mkrescue -o os.iso iso",
 "qemu-system-x86_64 -machine q35 -cdrom os.iso -d int"
]